### ISSUE TITLE
Wrong output for ksc-json-output in case of relative paths under Windows.

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_compiler#80]
I upgraded `ksv` to get support for [opaque types](https://github.com/kaitai-io/kaitai_struct_visualizer/issues/15) and with it came a changed interaction with `ksc`, the new `ksc-json-output` is used now. This leads to compile time errors in `ksv` for me, because your generated JSON doesn't seem to handle paths and their different representation in Java under different OS correctly. 

> C:/[...]/visualizer_main.rb:68:in `block (2 levels) in compile_formats': undefined method `[]' for nil:NilClass (NoMethodError)
        from C:/Program Files (x86)/kaitai_struct/visualizer/lib/kaitai/struct/visualizer/visualizer_main.rb:64:in `each'
        from C:/Program Files (x86)/kaitai_struct/visualizer/lib/kaitai/struct/visualizer/visualizer_main.rb:64:in `each_with_index'
        from C:/Program Files (x86)/kaitai_struct/visualizer/lib/kaitai/struct/visualizer/visualizer_main.rb:64:in `block in compile_formats'

``` Ruby
      fns.each_with_index { |fn, idx|
        puts "... processing #{fn} #{idx}"

        log_fn = log[fn]
        if log_fn['errors']
```

``` JSON
{"record\fmt_clt_recs.ksy": {"firstSpecName": "fmt_clt_recs","output": {"ruby": {"fmt_clt_recs": {"topLevelName": "FmtCltRecs","files": [{"fileName": "fmt_clt_recs.rb"}]},"fmt_oms_rec": {"topLevelName": "FmtOmsRec","files": [{"fileName": "fmt_oms_rec.rb"}]}}}},"record\fmt_oms_rec.ksy": {"firstSpecName": "fmt_oms_rec","output": {"ruby": {"fmt_oms_rec": {"topLevelName": "FmtOmsRec","files": [{"fileName": "fmt_oms_rec.rb"}]}}}}}
```

There are two problems here:

1. / to \

I use a command line similar to the following in Eclipse to start `ksv`:

> [...]ksv "${workspace_loc}/[...]/data.bin" "record/fmt_clt_recs.ksy" "record/fmt_oms_rec.ksy"

With the current `ksc` this leads to `\` instead of `/` in the generated JSON object, because Java internally uses a platform dependent path separator most of the times. The problem is that `ksv` sees `/` itself and can't find its own paths in the JSON anymore. I used `/` in favour of `\` simply because I had trouble using `\` in the past and `/` seems to be more common in Ruby, this would work on non-Windows etc.

2. Improper escaping of \

`\` needs to be escaped in JSON, that's why changing `/` to `\` in my invocation above doesn't fix the problem: JSON contains `\f` in the end instead of `\\f` which is what Ruby internally would have as the String key.

In my opinion, the best thing to do is simply to not generate `\` in JSON at all, so that only one normalized path separator is used across platforms and languages:

	  // FIXME: do proper string handling
	  def stringToJson(str: String): String =
	    "\"%s\"".format(str.replaceAll("\\\\", "/"))

This is somewhat hacky as well of course, but fixes the escape problem and makes interacting with `ksv` easier.

**Comment by GreyCat** [comment]
Thanks for reporting this! I've applied [slightly different fix](https://github.com/kaitai-io/kaitai_struct_compiler/commit/c94b65013b9a6826e4853074945645fab5738656) that reuses string output from BaseTranslator, so it should escape quotes, backslashes, etc, properly.

Probably it should be enough for Windows as well. As far as I understand, Ruby on Windows would do fine with backslashes as well. Can't check it, though, my Windows VM are not available at the moment. Could you check if this fix would work for you?

**Comment by tschoening** [comment]
If I use `\` in my relative paths, your change works, with `/` it doesn't. The problem is that the mentioned invocation with `/` works on all platforms and is part of some versioned Eclipse launch configuration. `\` will break that configuration for my colleagues using Linux.

Don't you think normalizing paths would be worth another hack? JSON itself is OS-independent, so providing such paths as well seems the right thing to do. We do that in some of our software as well for different runtimes and OS like Perl, which automatically convert `/` to `\` sometimes.

**Comment by GreyCat** [comment]
Ok, understood, I'll add normalization to `/` in file names then.

**Comment by GreyCat** [comment]
Should be fixed now: https://github.com/kaitai-io/kaitai_struct_compiler/commit/2aef0de69fe3197e07ee1812f3e611162d6fc62e

**Comment by tschoening** [comment]
Sorry, but I don't think so. Just tested with a current master and the error using `/` in my relative paths is still the same. Looking at your commit you seemed to have changes some error messages only? What I was talking about was the following line instead.

```
def stringToJson(str: String): String =
  translator.doStringLiteral(str)

https://github.com/kaitai-io/kaitai_struct_compiler/commit/c94b65013b9a6826e4853074945645fab5738656#diff-cd926bd86535fd1e7062bc1372c1ec7bR34

That line is providing either `/` or `\` to `ksv` depending on the current platform.

**Comment by GreyCat** [comment]
Could you provide an (preferably minimal) example of what is misbehaving? I'll try to find a Windows box to test shortly.

Current `stringToJson` method seems to do what it is supposed to do: it provides a JSON representation of an arbitrary string. There is absolutely no reason to do any string mangling in such generic method. If we need to replace backslashes in file paths somewhere, then we need to track that particular location and do replacement there.

**Comment by tschoening** [comment]
> Could you provide an (preferably minimal) example of what is misbehaving?

It's not necessarily a misbehaviour, but a design decision. Assume the tests-repo as current working dir, which of the following both invocations should work on Windows and why?

> ruby "-I[...]/kaitai_struct/runtime/ruby/lib" "[...]/kaitai_struct/visualizer/bin/ksv" "src/bcd_user_type_be.bin" "formats/bcd_user_type_be.ksy"

> ruby "-I[...]/kaitai_struct/runtime/ruby/lib" "[...]/kaitai_struct/visualizer/bin/ksv" "src/bcd_user_type_be.bin" "formats\bcd_user_type_be.ksy"

Currently, the first invocation doesn't work because of `formats/`, only the second one works. But that second invocation doesn't work on non-Windows.

So the question is, is it worth to add some workaround to JSON output to make the first invocation work on Windows as well? That way the first invocations should be shared amongst platforms easily.

The reason why the first invocation doesn't work is that `ksc` provides JSON with `\` on Windows always, because Java stringifies paths that way internally, while `ksv` simply uses what is given on the shell as text. So on Windows one needs to provide `\` on the shell, because that is what ends up in JSON, which doesn't work on non-Windows anymore, where Java internally stringifies to `/`.

If you disagree, just leave it as it is. The most important fix was that of the formal JSON syntax.

I have no other easier examples, my dir layout and such is completely different from yours. But things break down to the both provided invocations, assuming that `ksc` is properly available in the environment and such.
